// deno-lint-ignore-file

// This file is automatically generated by deno_bindgen.
// Do not edit this file directly.

const { dlopen } = Deno;

const { symbols } = dlopen("/workspace/litesvm/crates/deno-litesvm/../../target/debug/liblitesvm_deno.so", {
  create_default: {
    parameters: [],
    result: 'pointer',
    nonblocking: false
  },
  create_basic: {
    parameters: [],
    result: 'pointer',
    nonblocking: false
  },
  dispose: {
    parameters: [
      'pointer',
    ],
    result: 'void',
    nonblocking: false
  },
  set_default_programs: {
    parameters: [
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_precompiles: {
    parameters: [
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_builtins: {
    parameters: [
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_sysvars: {
    parameters: [
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  latest_blockhash: {
    parameters: [
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  expire_blockhash: {
    parameters: [
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  airdrop: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
      'u64',
    ],
    result: 'pointer',
    nonblocking: false
  },
  get_account: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_account: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  add_program: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  send_legacy_transaction: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  send_versioned_transaction: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  simulate_legacy_transaction: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  simulate_versioned_transaction: {
    parameters: [
      'pointer',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_transaction_history: {
    parameters: [
      'pointer',
      'u64',
    ],
    result: 'pointer',
    nonblocking: false
  },
  minimum_balance_for_rent_exemption: {
    parameters: [
      'pointer',
      'u64',
    ],
    result: 'pointer',
    nonblocking: false
  },
  latest_blockhash_string: {
    parameters: [
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
});

export function create_default(): LiteSvmHandle {
  const ret = symbols.create_default()
  return LiteSvmHandle.__constructor(ret);
}

export function create_basic(): LiteSvmHandle {
  const ret = symbols.create_basic()
  return LiteSvmHandle.__constructor(ret);
}

export function dispose(
  arg0: LiteSvmHandle,
): void {
  return symbols.dispose(
    arg0.ptr,
  )
}

export function set_default_programs(
  arg0: LiteSvmHandle,
): OperationResult {
  const ret = symbols.set_default_programs(
    arg0.ptr,
  )
  return OperationResult.__constructor(ret);
}

export function set_precompiles(
  arg0: LiteSvmHandle,
): OperationResult {
  const ret = symbols.set_precompiles(
    arg0.ptr,
  )
  return OperationResult.__constructor(ret);
}

export function set_builtins(
  arg0: LiteSvmHandle,
): OperationResult {
  const ret = symbols.set_builtins(
    arg0.ptr,
  )
  return OperationResult.__constructor(ret);
}

export function set_sysvars(
  arg0: LiteSvmHandle,
): OperationResult {
  const ret = symbols.set_sysvars(
    arg0.ptr,
  )
  return OperationResult.__constructor(ret);
}

export function latest_blockhash(
  arg0: LiteSvmHandle,
): BytesResult {
  const ret = symbols.latest_blockhash(
    arg0.ptr,
  )
  return BytesResult.__constructor(ret);
}

export function expire_blockhash(
  arg0: LiteSvmHandle,
): OperationResult {
  const ret = symbols.expire_blockhash(
    arg0.ptr,
  )
  return OperationResult.__constructor(ret);
}

export function airdrop(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
  arg2: number,
): OperationResult {
  const ret = symbols.airdrop(
    arg0.ptr,
    arg1,
    arg1.byteLength,
    arg2,
  )
  return OperationResult.__constructor(ret);
}

export function get_account(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
): AccountResult {
  const ret = symbols.get_account(
    arg0.ptr,
    arg1,
    arg1.byteLength,
  )
  return AccountResult.__constructor(ret);
}

export function set_account(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
  arg2: SerializableAccount,
): OperationResult {
  const ret = symbols.set_account(
    arg0.ptr,
    arg1,
    arg1.byteLength,
    arg2.ptr,
  )
  return OperationResult.__constructor(ret);
}

export function add_program(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
  arg2: Uint8Array,
): OperationResult {
  const ret = symbols.add_program(
    arg0.ptr,
    arg1,
    arg1.byteLength,
    arg2,
    arg2.byteLength,
  )
  return OperationResult.__constructor(ret);
}

export function send_legacy_transaction(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
): TransactionResponse {
  const ret = symbols.send_legacy_transaction(
    arg0.ptr,
    arg1,
    arg1.byteLength,
  )
  return TransactionResponse.__constructor(ret);
}

export function send_versioned_transaction(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
): TransactionResponse {
  const ret = symbols.send_versioned_transaction(
    arg0.ptr,
    arg1,
    arg1.byteLength,
  )
  return TransactionResponse.__constructor(ret);
}

export function simulate_legacy_transaction(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
): SimulationResponse {
  const ret = symbols.simulate_legacy_transaction(
    arg0.ptr,
    arg1,
    arg1.byteLength,
  )
  return SimulationResponse.__constructor(ret);
}

export function simulate_versioned_transaction(
  arg0: LiteSvmHandle,
  arg1: Uint8Array,
): SimulationResponse {
  const ret = symbols.simulate_versioned_transaction(
    arg0.ptr,
    arg1,
    arg1.byteLength,
  )
  return SimulationResponse.__constructor(ret);
}

export function set_transaction_history(
  arg0: LiteSvmHandle,
  arg1: number,
): OperationResult {
  const ret = symbols.set_transaction_history(
    arg0.ptr,
    arg1,
  )
  return OperationResult.__constructor(ret);
}

export function minimum_balance_for_rent_exemption(
  arg0: LiteSvmHandle,
  arg1: number,
): U64Result {
  const ret = symbols.minimum_balance_for_rent_exemption(
    arg0.ptr,
    arg1,
  )
  return U64Result.__constructor(ret);
}

export function latest_blockhash_string(
  arg0: LiteSvmHandle,
): StringResult {
  const ret = symbols.latest_blockhash_string(
    arg0.ptr,
  )
  return StringResult.__constructor(ret);
}

