// deno-lint-ignore-file

// This section is generated by deno_bindgen (inlined to avoid a separate bindings file).
const { dlopen } = Deno;

const { symbols } = dlopen("./../../target/debug/liblitesvm_deno.dylib", {
  create_default: {
    parameters: [],
    result: 'u32',
    nonblocking: false
  },
  create_basic: {
    parameters: [],
    result: 'u32',
    nonblocking: false
  },
  dispose: {
    parameters: [
      'u32',
    ],
    result: 'void',
    nonblocking: false
  },
  set_default_programs: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_precompiles: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_builtins: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_sysvars: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  latest_blockhash: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  expire_blockhash: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  airdrop: {
    parameters: [
      'u32',
      'buffer',
      'usize',
      'u64',
    ],
    result: 'pointer',
    nonblocking: false
  },
  get_account: {
    parameters: [
      'u32',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_account: {
    parameters: [
      'u32',
      'buffer',
      'usize',
      'pointer',
    ],
    result: 'pointer',
    nonblocking: false
  },
  add_program: {
    parameters: [
      'u32',
      'buffer',
      'usize',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  send_legacy_transaction: {
    parameters: [
      'u32',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  send_versioned_transaction: {
    parameters: [
      'u32',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  simulate_legacy_transaction: {
    parameters: [
      'u32',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  simulate_versioned_transaction: {
    parameters: [
      'u32',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  set_transaction_history: {
    parameters: [
      'u32',
      'u64',
    ],
    result: 'pointer',
    nonblocking: false
  },
  minimum_balance_for_rent_exemption: {
    parameters: [
      'u32',
      'u64',
    ],
    result: 'pointer',
    nonblocking: false
  },
  latest_blockhash_string: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  get_sysvar_clock: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  get_epoch_schedule: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
  warp_to_slot: {
    parameters: [
      'u32',
      'u64',
    ],
    result: 'pointer',
    nonblocking: false
  },
  get_transaction_by_sig: {
    parameters: [
      'u32',
      'buffer',
      'usize',
    ],
    result: 'pointer',
    nonblocking: false
  },
  get_all_account_keys: {
    parameters: [
      'u32',
    ],
    result: 'pointer',
    nonblocking: false
  },
});

export type LiteSvmHandle = number;

export interface SerializableAccount {
  lamports: number;
  data: Uint8Array;
  owner: Uint8Array;
  executable: boolean;
  rent_epoch: number;
}

export interface OperationResult {
  error?: string | null;
}

export interface BytesResult {
  value?: Uint8Array;
  error?: string | null;
}

export interface AccountResult {
  value?: SerializableAccount | null;
  error?: string | null;
}

/** Inner instruction produced during transaction execution */
export interface InnerInstruction {
  /** Index of the instruction in the transaction */
  instruction_index: number;
  /** Program ID that executed this instruction */
  program_id: Uint8Array;
  /** Instruction data */
  data: Uint8Array;
  /** Account indices involved */
  accounts: number[];
}

/** Return data from a program invocation */
export interface TransactionReturnData {
  /** Program ID that returned the data */
  program_id: Uint8Array;
  /** The returned data bytes */
  data: Uint8Array;
}

/** Metadata for a successfully executed transaction */
export interface TransactionMetadata {
  /** Transaction signature (64 bytes) */
  signature: Uint8Array;
  /** Program logs emitted during execution */
  logs: string[];
  /** Inner instructions grouped by instruction index */
  inner_instructions: InnerInstruction[][];
  /** Total compute units consumed */
  compute_units_consumed: number;
  /** Return data from the transaction */
  return_data: TransactionReturnData;
  /** Transaction fee in lamports */
  fee: number;
}

/** Metadata for a failed transaction */
export interface FailedTransactionMetadata {
  /** The error that caused the transaction to fail */
  err: TransactionError;
  /** Metadata captured before failure */
  meta: TransactionMetadata;
}

/** Transaction error types */
export type TransactionError =
  | { InstructionError: [number, InstructionError] }
  | { DuplicateInstruction: number }
  | { InsufficientFundsForRent: { account_index: number } }
  | string;

/** Instruction error types */
export type InstructionError =
  | { Custom: number }
  | "GenericError"
  | "InvalidArgument"
  | "InvalidInstructionData"
  | "InvalidAccountData"
  | "AccountDataTooSmall"
  | "InsufficientFunds"
  | "IncorrectProgramId"
  | "MissingRequiredSignature"
  | "AccountAlreadyInitialized"
  | "UninitializedAccount"
  | "NotEnoughAccountKeys"
  | "AccountBorrowFailed"
  | "MaxSeedLengthExceeded"
  | "InvalidSeeds"
  | string;

/** Result envelope for successful transaction */
export interface TransactionResultOk {
  status: "ok";
  signature: string; // base58-encoded signature
  logs: string[];
  inner_instructions: InnerInstruction[][];
  compute_units_consumed: number;
  return_data: {
    program_id: number[];
    data: number[];
  };
  fee: number;
}

/** Result envelope for failed transaction */
export interface TransactionResultErr {
  status: "err";
  err: TransactionError;
  meta: {
    signature: string; // base58-encoded signature
    logs: string[];
    inner_instructions: InnerInstruction[][];
    compute_units_consumed: number;
    return_data: {
      program_id: number[];
      data: number[];
    };
    fee: number;
  };
}

/** Transaction result envelope - matches LiteSVM's TransactionResult */
export type TransactionResultEnvelope = TransactionResultOk | TransactionResultErr;

/** Simulation result with post-execution account states */
export interface SimulationResultOk {
  status: "ok";
  meta: {
    signature: string; // base58-encoded signature
    logs: string[];
    inner_instructions: InnerInstruction[][];
    compute_units_consumed: number;
    return_data: {
      program_id: number[];
      data: number[];
    };
    fee: number;
  };
  post_accounts: Array<{
    pubkey: number[];
    account: SerializableAccount;
  }>;
}

/** Simulation result for failed simulation */
export interface SimulationResultErr {
  status: "err";
  err: TransactionError;
  meta: {
    signature: string; // base58-encoded signature
    logs: string[];
    inner_instructions: InnerInstruction[][];
    compute_units_consumed: number;
    return_data: {
      program_id: number[];
      data: number[];
    };
    fee: number;
  };
}

/** Simulation result envelope */
export type SimulationResultEnvelope = SimulationResultOk | SimulationResultErr;

export * from "./solana.ts";
import { PublicKey } from "./solana.ts";

export interface TransactionResponse {
  value?: TransactionResultEnvelope;
  error?: string | null;
}

export interface SimulationResponse {
  value?: SimulationResultEnvelope;
  error?: string | null;
}

export interface U64Result {
  value?: number;
  error?: string | null;
}

export interface StringResult {
  value?: string;
  error?: string | null;
}

const decoder = new TextDecoder();

function decodeResult<T>(ptr: Deno.PointerObject | null): T {
  if (ptr === null) throw new Error("LiteSVM returned null pointer");
  const view = new Deno.UnsafePointerView(ptr);
  const len = view.getUint32(0);
  // Read bytes manually since getArrayBuffer has issues with offsets
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = view.getUint8(4 + i);
  }
  const json = decoder.decode(bytes);
  return JSON.parse(json) as T;
}

export function create_default(): LiteSvmHandle {
  return symbols.create_default();
}

export function create_basic(): LiteSvmHandle {
  return symbols.create_basic();
}

export function dispose(handle: LiteSvmHandle): void {
  return symbols.dispose(handle);
}

export function set_default_programs(handle: LiteSvmHandle): OperationResult {
  return decodeResult(symbols.set_default_programs(handle));
}

export function set_precompiles(handle: LiteSvmHandle): OperationResult {
  return decodeResult(symbols.set_precompiles(handle));
}

export function set_builtins(handle: LiteSvmHandle): OperationResult {
  return decodeResult(symbols.set_builtins(handle));
}

export function set_sysvars(handle: LiteSvmHandle): OperationResult {
  return decodeResult(symbols.set_sysvars(handle));
}

export function latest_blockhash(handle: LiteSvmHandle): BytesResult {
  return decodeResult(symbols.latest_blockhash(handle));
}

export function expire_blockhash(handle: LiteSvmHandle): OperationResult {
  return decodeResult(symbols.expire_blockhash(handle));
}

export function airdrop(handle: LiteSvmHandle, pubkey: Uint8Array, lamports: number): OperationResult {
  const pubkeyBuf = new Uint8Array(pubkey);
  return decodeResult(symbols.airdrop(handle, pubkeyBuf, BigInt(pubkeyBuf.byteLength), BigInt(lamports)));
}

export function get_account(handle: LiteSvmHandle, pubkey: Uint8Array): AccountResult {
  const pubkeyBuf = new Uint8Array(pubkey);
  return decodeResult(symbols.get_account(handle, pubkeyBuf, BigInt(pubkeyBuf.byteLength)));
}

export function set_account(
  handle: LiteSvmHandle,
  pubkey: Uint8Array,
  account: SerializableAccount,
): OperationResult {
  // Convert Uint8Array fields to regular arrays for proper JSON serialization
  const accountForJson = {
    lamports: account.lamports,
    data: Array.from(account.data),
    owner: Array.from(account.owner),
    executable: account.executable,
    rent_epoch: account.rent_epoch,
  };
  // Serialize account as length-prefixed JSON for FFI
  const jsonBytes = new TextEncoder().encode(JSON.stringify(accountForJson));
  // Create buffer with 4-byte length prefix + JSON data
  const encoded = new Uint8Array(4 + jsonBytes.length);
  const dataView = new DataView(encoded.buffer);
  dataView.setUint32(0, jsonBytes.length, true); // little-endian
  encoded.set(jsonBytes, 4);
  const ptr = Deno.UnsafePointer.of(encoded);
  if (!ptr) {
    throw new Error("Failed to create pointer for account data");
  }
  const pubkeyBuf = new Uint8Array(pubkey);
  return decodeResult(symbols.set_account(handle, pubkeyBuf, BigInt(pubkeyBuf.byteLength), ptr));
}

export function add_program(
  handle: LiteSvmHandle,
  programId: Uint8Array,
  programBytes: Uint8Array,
): OperationResult {
  const id = new Uint8Array(programId);
  const elf = new Uint8Array(programBytes);
  return decodeResult(
    symbols.add_program(
      handle,
      id,
      BigInt(id.byteLength),
      elf,
      BigInt(elf.byteLength),
    ),
  );
}

export function send_legacy_transaction(handle: LiteSvmHandle, txBytes: Uint8Array): TransactionResponse {
  const tx = new Uint8Array(txBytes);
  return decodeResult(symbols.send_legacy_transaction(handle, tx, BigInt(tx.byteLength)));
}

export function send_versioned_transaction(handle: LiteSvmHandle, txBytes: Uint8Array): TransactionResponse {
  const tx = new Uint8Array(txBytes);
  return decodeResult(symbols.send_versioned_transaction(handle, tx, BigInt(tx.byteLength)));
}

export function simulate_legacy_transaction(handle: LiteSvmHandle, txBytes: Uint8Array): SimulationResponse {
  const tx = new Uint8Array(txBytes);
  return decodeResult(symbols.simulate_legacy_transaction(handle, tx, BigInt(tx.byteLength)));
}

export function simulate_versioned_transaction(handle: LiteSvmHandle, txBytes: Uint8Array): SimulationResponse {
  const tx = new Uint8Array(txBytes);
  return decodeResult(symbols.simulate_versioned_transaction(handle, tx, BigInt(tx.byteLength)));
}

export function set_transaction_history(handle: LiteSvmHandle, capacity: number): OperationResult {
  return decodeResult(symbols.set_transaction_history(handle, BigInt(capacity)));
}

export function minimum_balance_for_rent_exemption(handle: LiteSvmHandle, dataLength: number): U64Result {
  return decodeResult(symbols.minimum_balance_for_rent_exemption(handle, BigInt(dataLength)));
}

export function latest_blockhash_string(handle: LiteSvmHandle): StringResult {
  return decodeResult(symbols.latest_blockhash_string(handle));
}

// ============================================================================
// New FFI result types and wrapper functions
// ============================================================================

export interface ClockInfo {
  slot: number;
  epoch: number;
  unix_timestamp: number;
  leader_schedule_epoch: number;
  epoch_start_timestamp: number;
}

export interface ClockInfoResult {
  value?: ClockInfo;
  error?: string | null;
}

export interface EpochScheduleInfo {
  slots_per_epoch: number;
  leader_schedule_slot_offset: number;
  warmup: boolean;
  first_normal_epoch: number;
  first_normal_slot: number;
}

export interface EpochScheduleInfoResult {
  value?: EpochScheduleInfo;
  error?: string | null;
}

export interface AccountKeysResult {
  value?: number[][];
  error?: string | null;
}

export function get_sysvar_clock(handle: LiteSvmHandle): ClockInfoResult {
  return decodeResult(symbols.get_sysvar_clock(handle));
}

export function get_epoch_schedule(handle: LiteSvmHandle): EpochScheduleInfoResult {
  return decodeResult(symbols.get_epoch_schedule(handle));
}

export function warp_to_slot(handle: LiteSvmHandle, slot: number): OperationResult {
  return decodeResult(symbols.warp_to_slot(handle, BigInt(slot)));
}

export function get_transaction_by_sig(handle: LiteSvmHandle, signature: Uint8Array): TransactionResponse {
  // Safety: FFI requires non-null pointer; reject invalid signatures at the TS level
  if (signature.length !== 64) {
    return { value: undefined, error: "expected 64 byte signature" };
  }
  const sigBuf = new Uint8Array(signature);
  return decodeResult(symbols.get_transaction_by_sig(handle, sigBuf, BigInt(sigBuf.byteLength)));
}

export function get_all_account_keys(handle: LiteSvmHandle): AccountKeysResult {
  return decodeResult(symbols.get_all_account_keys(handle));
}

// Ergonomic wrapper built on top of the raw bindings above.
type Handle = LiteSvmHandle;

type TransactionResult = TransactionResultEnvelope;
type SimulationResult = SimulationResultEnvelope;

type SerializableAccountType = SerializableAccount;

function unwrapVoid(result: { error?: string | null }): void {
  if (result.error) {
    throw new Error(result.error);
  }
}

function unwrapValue<T>(result: { value?: T; error?: string | null }): T {
  if (result.error) {
    throw new Error(result.error);
  }

  if (result.value === undefined) {
    throw new Error("LiteSVM binding returned no value");
  }

  return result.value;
}

function unwrapOptionalValue<T>(result: {
  value?: T | null;
  error?: string | null;
}): T | null {
  if (result.error) {
    throw new Error(result.error);
  }

  return result.value ?? null;
}

// JSON form of SerializableAccount (with arrays instead of Uint8Array)
interface SerializableAccountJson {
  lamports: number;
  data: number[];
  owner: number[];
  executable: boolean;
  rent_epoch: number;
}

// Convert JSON account (with arrays) to SerializableAccount (with Uint8Arrays)
function convertAccountFromJson(
  account: SerializableAccountJson | null | undefined
): SerializableAccount | null {
  if (account === null || account === undefined) {
    return null;
  }
  return {
    lamports: account.lamports,
    data: new Uint8Array(account.data),
    owner: new Uint8Array(account.owner),
    executable: account.executable,
    rent_epoch: account.rent_epoch,
  };
}

export interface LiteSvmOptions {
  /**
   * Start with an empty LiteSVM without default programs or sysvars.
   * Useful for fine-grained control when bootstrapping.
   */
  basic?: boolean;
}

import {
  TOKEN_ACCOUNT_SIZE,
  TOKEN_PROGRAM_PUBKEY,
  TOKEN_ACCOUNT_RENT_EXEMPTION,
} from "./utils.ts";

export class LiteSvm {
  #handle: Handle;

  constructor(opts: LiteSvmOptions = {}) {
    // Note: create_basic() calls LiteSVM::new() which includes full setup
    // (sysvars, programs, builtins), while create_default() calls
    // LiteSVM::default() which is a bare instance.
    this.#handle = opts.basic ? create_default() : create_basic();
  }

  dispose(): void {
    dispose(this.#handle);
  }

  latestBlockhash(): Uint8Array {
    return unwrapValue(latest_blockhash(this.#handle));
  }

  latestBlockhashString(): string {
    return unwrapValue(latest_blockhash_string(this.#handle));
  }

  expireBlockhash(): void {
    unwrapVoid(expire_blockhash(this.#handle));
  }

  setDefaultPrograms(): void {
    unwrapVoid(set_default_programs(this.#handle));
  }

  setPrecompiles(): void {
    unwrapVoid(set_precompiles(this.#handle));
  }

  setBuiltins(): void {
    unwrapVoid(set_builtins(this.#handle));
  }

  setSysvars(): void {
    unwrapVoid(set_sysvars(this.#handle));
  }

  airdrop(pubkey: Uint8Array, lamports: bigint | number): void {
    const value = typeof lamports === "bigint" ? Number(lamports) : lamports;
    unwrapVoid(airdrop(this.#handle, pubkey, value));
  }

  getAccount(pubkey: Uint8Array): SerializableAccountType | null {
    const result = get_account(this.#handle, pubkey);
    if (result.error) {
      throw new Error(result.error);
    }
    // The result.value is typed as SerializableAccount but actually comes from JSON
    // with arrays instead of Uint8Array, so we cast and convert
    return convertAccountFromJson(result.value as unknown as SerializableAccountJson | null);
  }

  setAccount(pubkey: Uint8Array, account: SerializableAccountType): void {
    unwrapVoid(set_account(this.#handle, pubkey, account));
  }

  addProgram(programId: Uint8Array, programBytes: Uint8Array): void {
    unwrapVoid(add_program(this.#handle, programId, programBytes));
  }

  sendLegacyTransaction(bytes: Uint8Array): TransactionResult {
    return unwrapValue(send_legacy_transaction(this.#handle, bytes));
  }

  sendVersionedTransaction(bytes: Uint8Array): TransactionResult {
    return unwrapValue(send_versioned_transaction(this.#handle, bytes));
  }

  simulateLegacyTransaction(bytes: Uint8Array): SimulationResult {
    return unwrapValue(simulate_legacy_transaction(this.#handle, bytes));
  }

  simulateVersionedTransaction(bytes: Uint8Array): SimulationResult {
    return unwrapValue(simulate_versioned_transaction(this.#handle, bytes));
  }

  setTransactionHistory(capacity: number): void {
    unwrapVoid(set_transaction_history(this.#handle, capacity));
  }

  minimumBalanceForRentExemption(dataLength: number): number {
    return Number(
      unwrapValue(minimum_balance_for_rent_exemption(this.#handle, dataLength)),
    );
  }

  // --------------------------------------------------------------------------
  // Sysvar & slot access
  // --------------------------------------------------------------------------

  /** Get the current Clock sysvar (slot, epoch, timestamps) */
  getClockInfo(): ClockInfo {
    return unwrapValue(get_sysvar_clock(this.#handle));
  }

  /** Get the EpochSchedule sysvar */
  getEpochSchedule(): EpochScheduleInfo {
    return unwrapValue(get_epoch_schedule(this.#handle));
  }

  /** Advance the SVM clock to a specific slot */
  warpToSlot(slot: number): void {
    unwrapVoid(warp_to_slot(this.#handle, slot));
  }

  // --------------------------------------------------------------------------
  // Transaction history
  // --------------------------------------------------------------------------

  /** Look up a transaction by its 64-byte signature */
  getTransactionBySignature(signature: Uint8Array): TransactionResultEnvelope | null {
    return unwrapOptionalValue(get_transaction_by_sig(this.#handle, signature));
  }

  // --------------------------------------------------------------------------
  // Account iteration
  // --------------------------------------------------------------------------

  /** Get all account pubkeys known to the SVM (as 32-byte Uint8Arrays) */
  getAllAccountKeys(): Uint8Array[] {
    const raw = unwrapValue(get_all_account_keys(this.#handle));
    return raw.map((bytes: number[]) => new Uint8Array(bytes));
  }

  // --------------------------------------------------------------------------
  // Token helpers
  // --------------------------------------------------------------------------

  /**
   * Sets a token balance for an account, creating or overwriting the token
   * account data. Use this for testing to assume any token balance without
   * needing actual mints or token issuance.
   */
  setTokenBalance(opts: {
    tokenAccount: PublicKey;
    mint: PublicKey;
    owner: PublicKey;
    amount: bigint;
  }): void {
    const data = new Uint8Array(TOKEN_ACCOUNT_SIZE);
    const view = new DataView(data.buffer);

    data.set(opts.mint.toBytes(), 0);       // mint at 0
    data.set(opts.owner.toBytes(), 32);      // owner at 32
    view.setBigUint64(64, opts.amount, true); // amount at 64
    view.setUint32(72, 0, true);             // delegate: None
    data[108] = 1;                           // state: Initialized
    view.setUint32(109, 0, true);            // is_native: None
    view.setBigUint64(121, BigInt(0), true); // delegated_amount
    view.setUint32(129, 0, true);            // close_authority: None

    const account: SerializableAccount = {
      lamports: TOKEN_ACCOUNT_RENT_EXEMPTION,
      data,
      owner: new PublicKey(TOKEN_PROGRAM_PUBKEY).toBytes(),
      executable: false,
      rent_epoch: 0,
    };

    this.setAccount(opts.tokenAccount.toBytes(), account);
  }

  /**
   * Modifies only the balance of an existing token account, preserving all
   * other fields (mint, owner, delegate, etc.).
   */
  modifyTokenBalance(tokenAccount: PublicKey, newAmount: bigint): void {
    const existing = this.getAccount(tokenAccount.toBytes());
    if (!existing) {
      throw new Error(`Token account ${tokenAccount.toBase58()} does not exist`);
    }

    const data = new Uint8Array(existing.data);
    new DataView(data.buffer).setBigUint64(64, newAmount, true);

    this.setAccount(tokenAccount.toBytes(), { ...existing, data });
  }

  /**
   * Reads the token balance from an existing token account.
   */
  getTokenBalance(tokenAccount: PublicKey): bigint {
    const existing = this.getAccount(tokenAccount.toBytes());
    if (!existing) {
      throw new Error(`Token account ${tokenAccount.toBase58()} does not exist`);
    }
    if (existing.data.length < TOKEN_ACCOUNT_SIZE) {
      throw new Error(`Invalid token account data length: ${existing.data.length}`);
    }

    return new DataView(
      existing.data.buffer,
      existing.data.byteOffset,
      existing.data.byteLength,
    ).getBigUint64(64, true);
  }
}

export const createBasic = create_basic;
export const createDefault = create_default;
